cluster:
  enabled: true

metrics:
  enabled: true
  serviceMonitor:
    enabled: true

externalS3:
  enabled: true
  host: s3.amazonaws.com
  port: 443
  rootPath: files
  useSSL: true
  useIAM: true
  bucketName: "${MILVUS_BUCKET_NAME}"

persistence:
  enabled: true
  storageClass: milvus-storage

proxy:
  replicas: 3
  resources:
    requests:
      memory: "2Gi"
      cpu: "1"
    limits:
      memory: "4Gi"
      cpu: "2"

queryNode:
  replicas: 3
  resources:
    requests:
      memory: "4Gi"
      cpu: "2"
    limits:
      memory: "8Gi"
      cpu: "4"

dataNode:
  replicas: 3
  resources:
    requests:
      memory: "4Gi"
      cpu: "2"
    limits:
      memory: "8Gi"
      cpu: "4"

indexNode:
  replicas: 2
  resources:
    requests:
      memory: "4Gi"
      cpu: "2"
    limits:
      memory: "8Gi"
      cpu: "4"

security:
  enabled: true
  ssl:
    enabled: true
  authentication:
    enabled: true
    credentials:
      username: "${MILVUS_USER}"
      password: "${MILVUS_PASSWORD}"

monitoring:
  prometheus:
    enabled: true
    serviceMonitor:
      enabled: true
  grafana:
    enabled: true
    dashboards:
      enabled: true

# Default collection settings
defaultCollectionProperties:
  autoID: false
  vectorField: "vec"
  primaryKeyField: "id"
  vectorDim: 1024  # Based on our setup in milvus_spark.py

# Index settings
indexSettings:
  type: "IVF_FLAT"
  metricType: "IP"
  params:
    nlist: 1024

# Storage configuration
storage:
  type: "minio"
  minio:
    address: "${MINIO_ADDRESS:-localhost}"
    port: 9000
    accessKey: "${MINIO_ACCESS_KEY:-minioadmin}"
    secretKey: "${MINIO_SECRET_KEY:-minioadmin}"
    useSSL: false
    bucketName: "${MILVUS_BUCKET_NAME}"
    rootPath: "files"

# Database configuration
database:
  name: "default" 